# Generated by Django 5.2.7 on 2025-10-08 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='name',
            field=models.TextField(editable=False, unique=True),
        ),
        migrations.CreateModel(
            name='BattlePokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.TextField(null=True)),
                ('pokemon_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemons.pokemon')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('favorite_pokemon', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pokemons.pokemon')),
                ('team_battle', models.ManyToManyField(to='pokemons.battlepokemon')),
            ],
        ),
        migrations.AddField(
            model_name='battlepokemon',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemons.user'),
        ),
    ]
