# Generated by Django 5.2.7 on 2025-10-08 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0002_alter_pokemon_name_battlepokemon_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battlepokemon',
            name='alias',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='battlepokemon',
            name='pokemon_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokemon', to='pokemons.pokemon'),
        ),
        migrations.AlterField(
            model_name='battlepokemon',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='pokemons.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='team_battle',
            field=models.ManyToManyField(related_name='pokemons_team', to='pokemons.battlepokemon'),
        ),
    ]
